---
global:
  pattern: multicloud-gitops
  singleArgoCD: true
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  variant: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
clusterGroup:
  argoCD:
    initContainers: 
    - args:
      - -c
      - cp /etc/kustomize/plugin/my-plugin /kustomize-plugin
      command:
      - /bin/bash
      image: registry.example.com/kustomize/kustomize-plugin:latest
      name: kustomize-plugin-install
      volumeMounts:
      - mountPath: /kustomize-plugin
        name: kustomize-plugin-dir
    volumeMounts:
    - mountPath: /etc/kustomize/plugin
      name: kustomize-plugin-dir
    volumes:                                                                     
    - emptyDir: {}
      name: kustomize-plugin-dir    
    env: 
    - name: KUSTOMIZE_PLUGIN_HOME                                              
      value: "/etc/kustomize/plugin"      